#!/bin/bash

pidfile="/run/user/$(id -u)/compton.pid"
if ! [ -e "$pidfile" ]; then
	compton &>> ~/.xsession-errors & disown
	printf "%s" "$!" > "$pidfile"
else
	printf "compositor is already running\n"
	exit 1
fi

if [ "$1" = "--icon" ]; then
	printf "%s\n" $'\uf302' # "images"
fi
