#!/bin/bash

pidfile="/run/user/$(id -u)/picom.pid"
if ! [ -e "$pidfile" ]; then
	picom --daemon --write-pid-path "$pidfile" &>> ~/.xsession-errors
	# printf "%s" "$!" > "$pidfile"
# else
# 	printf "compositor is already running\n"
# 	exit 1
fi

if [ "$1" = "--icon" ]; then
	printf "%s\n" $'\uf302' # "images"
fi
